### ISSUE TITLE
Dhruv's comments

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-yang-message-broker-integration#1]
- It would be good to also expand on how the manual system works for a reader to be able to appreciate the motivation for native integration. 
- Explain the relationship between message broker (in initial sections) and Time Series DB (in section 3). The figure in section 3 does not have any mention of YANG message broker producer and consumer for instance. 
- Section 4 and 5 are better suited as appendix
- Section 7, consider using RFC 7942 template
- Use RFC 8792to handle long lines

**Comment by graf3net** [comment]
addressed in -01
