### ISSUE TITLE
Feng's comments

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-yang-message-broker-integration#2]
I suggest use yang library of one network node to build one YANG schema context, and then register to schema register instead of registeration per subscription. It may cause many unuseful yang modules, but it should be helpful for any data validation and need not modify yang library definition(e.g. add augmention list).
  Anydata node, I think, MUST be validated by the schema context which it belongs to, it's not really modelled by any YANG schema.

**Comment by graf3net** [comment]
addressed in -01
