### ISSUE TITLE
Andy's comment

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-yang-message-broker-integration#3]
I think the scope of this standards work is very important, and quite challenging to get right.

We have a program (work-in-progress) called yangcli-gw, but it is not open-source.
The documentation is publicly available
[https://docs.yumaworks.com/en/latest/yangcli-gw/introduction.html](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.yumaworks.com%2Fen%2Flatest%2Fyangcli-gw%2Fintroduction.html&data=05%7C02%7Cmohamed.boucadair%40orange.com%7Cd020c17f5c4b4fa545fd08dc660be874%7C90c7a20af34b40bfbc48b9253b6f5d20%7C0%7C0%7C638497448531477362%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=huRFIslYiVvZ7wOsCpoQU%2F%2BF%2FYl6CLE8eIh87JBdALE%3D&reserved=0)

I created a protocol called ZMQAPI
[https://docs.yumaworks.com/en/latest/yangcli-gw/zmqapi-intro.html](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.yumaworks.com%2Fen%2Flatest%2Fyangcli-gw%2Fzmqapi-intro.html&data=05%7C02%7Cmohamed.boucadair%40orange.com%7Cd020c17f5c4b4fa545fd08dc660be874%7C90c7a20af34b40bfbc48b9253b6f5d20%7C0%7C0%7C638497448531496921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=eX2EMQZEqPAm3ZBlPKte1fSUEJ8BSuLSCQVi%2FRnUtCg%3D&reserved=0)

It uses a YANG module to define structures to represent the message layers
[https://github.com/YumaWorks/yumapro-yang/blob/main/yumaworks/yumaworks-zmqapi.yang](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FYumaWorks%2Fyumapro-yang%2Fblob%2Fmain%2Fyumaworks%2Fyumaworks-zmqapi.yang&data=05%7C02%7Cmohamed.boucadair%40orange.com%7Cd020c17f5c4b4fa545fd08dc660be874%7C90c7a20af34b40bfbc48b9253b6f5d20%7C0%7C0%7C638497448531511644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=kstufRfSt5ORZ%2FT7nk4NMhiURkzOvs2AxsM3SoLKX%2F4%3D&reserved=0)

IMO it should be possible to define the message format as a YANG structure in 1 draft
and message broker bindings in other drafts.

**Comment by graf3net** [comment]
addressed in -01
