### ISSUE TITLE
Qin's comments

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-nmop/draft-ietf-nmop-yang-message-broker-integration#4]
A few comments for your considering:
1.	For YANG-Push to Message Broker Integration, as described in section 1.3, both configured subscription and dynamic subscription can be supported, however look at the end to end work flow in figure 1, only static subscription or configured subscription is supported, see step (2) (4), can you clarify whether dynamic subscription is supported?
2.	Given client server series drafts have been moved to RFC queue for publication, have you considered to implement these client server series draft and integrated them into message broker?
3.	How do you see the difference between this work and draft-lindblad-tlm-philatelist, especially time series database integration
4.	[I-D.tgraf-netconf-yang-push-observation-time] introduce two type of timestamps, I am wondering whether these two type of timestamps will be used as time stamp for time series database or 
Time Series Database Ingestion will generate its own timestamp when receiving Kafka message?

**Comment by graf3net** [comment]
addressed in -01
